### PR TITLE
Move strings from here to lib-cove-web

### PR DESCRIPTION
**Pull request by Bjwebb**
Corresponding lib-cove-web PR is https://github.com/OpenDataServices/lib-cove-web/pull/58

### CODE REVIEW

**Comment by Bjwebb** [comment]
@jpmckinney I still need to ensure tests pass on CI, but this is ready for a look through (I can't assign you as reviewer). Still to come are PRs on cove-oc4ids and flatten-tool.

**Comment by michaelwood** [comment]
I think we can remove Django and bleach from the dependencies in setup.py?

**Review by michaelwood — COMMENTED** [review]
I think we can remove Django and bleach from the dependencies in setup.py?

**Review by michaelwood — APPROVED** [review]

**Comment by jpmckinney** [comment]
Note that this broke tests on lib-cove-ocds, which expected `<code>` to appear in `message_safe`, and expected the "is too short" message to have been overridden: c6c150f4aa10e58cccf58adfcbe9c7545c007972

**Pull request merged**
