### PR TITLE
Use for-loop instead of slower any() with generator expression

### PR DESCRIPTION
**Pull request by jpmckinney**
Drops time spent in type validator from 13% to 7%

Before:

output2

After:

output

### CODE REVIEW

**Comment by jpmckinney** [comment]
https://github.com/OpenDataServices/cove/pull/609/files#diff-e4978c21ecf1ac03267a96314f0f0e88 added an early return in `JsonRefResolver` which skipped over `add_is_codelist`. If I `git checkout HEAD~1` from that commit, the code doesn't have the early return. So, I think it was introduced in error.

**Review by Bjwebb — APPROVED** [review]

**Comment by Bjwebb** [comment]
This is causing the lib-cove-oc4ids tests to fail, and I've not had chance to dig into what's going on, so leaving this unmerged for now.

**Comment by jpmckinney** [comment]
I think 3a67f14 wasn't working as expected, because it was being called on non-dereferenced schema.

**Comment by jpmckinney** [comment]
Re-measuring using the commands in https://github.com/open-contracting/lib-cove-oc4ids/issues/23, the time spent in the type validator drops from 10% to 6%.

Before:

output2

After:

output

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
