### PR TITLE
release: 0.31.0 (@jpmckinney's changes)

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Could #121 be included? Any environment with flattentool already installed won’t see a change.

Also I think the OCDS integration should pass now. Locking to a specific version makes the integration test a little less useful.

**Comment by jpmckinney** [comment]
Ah, I see you're cloning lib-cove-ocds. If you pip install it, then you'll always get a version that works with cove-ocds, because cove-ocds only uses released versions.

**Review by odscjames — APPROVED** [review]
Are we sure the jsonschema validator changes are backwards compatible with earlier versions of that library?

**Comment by odscjames** [comment]
(I'll leave Q about #121 to Ben; I don't know if it's better to get this out today and look at that later, I suspect there might be some cans of worms there so that seems good to me)

**Comment by Bjwebb** [comment]
I've tested this with older jsonschema, and it seems to work fine.

#121 is not included, but I will look at that next.

**Comment by Bjwebb** [comment]
I've released this on PyPI.

**Comment by jpmckinney** [comment]
Thank you!

**Comment by jpmckinney** [comment]
In terms of OCP's needs, #123 is higher priority than #121.

Besides jsonschema compatibility, #123 allows lib-cove-ocds to control `$ref` resolution. There are other ways of satisfying the latter. This is getting in the way of some improvements (unless we start publishing releases of the fork).

**Pull request merged**
