### PR TITLE
fix: non-unique int IDs

### LINKED ISSUE #101: non-unique IDs on array items
From https://github.com/open-contracting/lib-cove-ocds/issues/104#issuecomment-1264228009
```
sequence item 0: expected str instance, int found
```

It happens when lib-cove expects unique identifiers (string type) on array items

### PR DESCRIPTION
**Pull request by Ravf95**
Closes #101

### CODE REVIEW

**Comment by radix0000** [comment]
We have made changes to the main branch which should fix the linting issue. You will need to rebase your branch, but hopefully after that the issue will go away. Thanks.

**Comment by jpmckinney** [comment]
See #102 for new PR addressing review.

**Comment by jpmckinney** [comment]
Test failures are because the type-change to `str` needs to be done when creating the validation error, not when checking for duplicates. This PR means `"1"` (str) is a duplicate of `1` (int). One might argue that they should be considered duplicates, but that would be a significant change in behavior.

**Comment by odscjames** [comment]
Closing in favour of  #106

**Pull request closed without merging**
