### PR TITLE
Calculate additional codelist values for schema using anyOf

### PR DESCRIPTION
**Pull request by odscjames**
Like OCDS record packages

https://github.com/OpenDataServices/lib-cove/pull/125 https://github.com/open-contracting/lib-cove-ocds/issues/106

### CODE REVIEW

**Comment by odscjames** [comment]
@jpmckinney I wanted to simplify the tests, so we didn't also have to change the check for local or remote schemas. Does this still capture the change you are after?

**Comment by jpmckinney** [comment]
The integration.yml changes from #125 are relevant - otherwise these tests will forever fail.

The change to `if schema_url.startswith("http")` needs to be carried over. It's necessary to "fix(custom_jsonref_jsonloader): Read from filesystem if schema_url is a file path", because lib-cove has already messed around with the `uri` value by this point, and checking `schema_url` directly is the only way to know if the original url was a file path or not.

As for the test, if it fails without the changes to common.py (and passes with the changes), then that's what matters.

**Comment by odscjames** [comment]
> The integration.yml changes from https://github.com/OpenDataServices/lib-cove/pull/125 are relevant - otherwise these tests will forever fail.

It's on my todo list and I was going to look at separately

>  The change to if schema_url.startswith("http")  ....

Noted in seperate issue to check out - thanks.

> As for the test, if it fails without the changes to common.py (and passes with the changes), then that's what matters.

It does!

**Comment by odscjames** [comment]
@jpmckinney  - @Bjwebb has pointed out the comments are anyOf but the code is oneOf - it should be doing this for both right? If so I can just add this and we should be done:

```
elif "anyOf" in value and isinstance(value["anyOf"], list):
            descendants = value["anyOf"]
```

**Comment by jpmckinney** [comment]
I probably meant oneOf everywhere (OCDS doesn't use anyOf), but supporting anyOf should be the same logic, so that change sounds good.

**Comment by odscjames** [comment]
Added.

I don't think we need a special test just for that elif - if I change schema_with_oneof_codelists.json locally I can see it working for anyOf too.

But over to @Bjwebb to review!

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
