### PR TITLE
Prepare 0.4.0 release

### PR DESCRIPTION
**Pull request by Bjwebb**
Next steps:
- [ ] Merge this
- [ ] Tag the branch
- [ ] Update this PR to use the tagged release in requirements - https://github.com/OpenDataServices/cove/pull/1140

### CODE REVIEW

**Comment by Bjwebb** [comment]
This diff between the last release, and this release branch is useful: 
https://github.com/OpenDataServices/lib-cove/compare/v0.3.1..release-0.4.0

**Comment by Bjwebb** [comment]
@BibianaC @kindly Should this PR have an entry in the CHANGELOG https://github.com/OpenDataServices/lib-cove/compare/v0.3.1..release-0.4.0

**Comment by BibianaC** [comment]
@Bjwebb do you want me to add the entry in this PR?

**Comment by Bjwebb** [comment]
@BibianaC Yes please.

**Comment by BibianaC** [comment]
@Bjwebb done!

**Comment by odscjames** [comment]
setup.py should have it's versioned bumped as well. 

Rest looks fine

**Comment by BibianaC** [comment]
@odscjames thanks for to spot this. I have updated `setup.py`

**Pull request merged**
